POST https://beauty-connect-server.onrender.com/videos
Content-Type: application/json

{
  "title": "Video Node",
  "description": "Description 1",
  "duration": "180"
}

###
GET https://beauty-connect-server.onrender.com/videos

###
PUT https://beauty-connect-server.onrender.com/videos/4
Content-Type: application/json

{
  "title": "Video Atualizado",
  "description": "Description 1",
  "duration": "80"
}

###
DELETE https://beauty-connect-server.onrender.com/videos/5
